// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NVR.Infrastructure.Data;

#nullable disable

namespace NVR.Infrastructure.Migrations
{
    [DbContext(typeof(NvrDbContext))]
    [Migration("20260228151636_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NVR.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NVR.Core.Entities.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AudioEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Framerate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecording")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnvifServiceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PtzCapable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resolution_Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resolution_Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RtspUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StorageProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("Status");

                    b.HasIndex("StorageProfileId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("NVR.Core.Entities.CameraAnalyticsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("AvgBitrateKbps")
                        .HasColumnType("REAL");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("TEXT");

                    b.Property<int>("MotionEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageBytesWritten")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UptimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CameraId", "Hour")
                        .IsUnique();

                    b.ToTable("CameraAnalyticsSnapshots");
                });

            modelBuilder.Entity("NVR.Core.Entities.CameraEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("Timestamp");

                    b.HasIndex("CameraId", "Timestamp");

                    b.ToTable("CameraEvents");
                });

            modelBuilder.Entity("NVR.Core.Entities.CameraUserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CameraId", "UserId");

                    b.ToTable("CameraUserAccesses");
                });

            modelBuilder.Entity("NVR.Core.Entities.PtzPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnvifToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("PanPosition")
                        .HasColumnType("REAL");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<float?>("TiltPosition")
                        .HasColumnType("REAL");

                    b.Property<float?>("ZoomPosition")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("PtzPresets");
                });

            modelBuilder.Entity("NVR.Core.Entities.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeleteScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Framerate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAudio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndexPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.HasIndex("StorageProfileId");

                    b.HasIndex("CameraId", "StartTime");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("NVR.Core.Entities.RecordingChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMotion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyframeIndex")
                        .HasColumnType("TEXT");

                    b.Property<float?>("MotionScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("StartTime");

                    b.HasIndex("CameraId", "StartTime");

                    b.ToTable("RecordingChunks");
                });

            modelBuilder.Entity("NVR.Core.Entities.RecordingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Continuous")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("RecordingSchedules");
                });

            modelBuilder.Entity("NVR.Core.Entities.StorageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoDeleteEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<int>("LowSpaceWarningPercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UsedStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageProfiles");
                });

            modelBuilder.Entity("NVR.Core.Entities.StreamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesStreamed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FramesSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("UserId");

                    b.HasIndex("IsActive", "SessionType");

                    b.ToTable("StreamSessions");
                });

            modelBuilder.Entity("NVR.Core.Entities.SystemAnalyticsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AcknowledgedAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnlineCameras")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeakConcurrentViewers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordingCameras")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StorageUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCameras")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMotionEvents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalRecordingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalStorageBytesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalStorageBytesWritten")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalViewerSessions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("SystemAnalyticsSnapshots");
                });

            modelBuilder.Entity("NVR.Core.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("NVR.Core.Entities.UserCameraLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GridColumns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("UserId", "LayoutName", "GridPosition")
                        .IsUnique();

                    b.ToTable("UserCameraLayouts");
                });

            modelBuilder.Entity("NVR.Core.Entities.Camera", b =>
                {
                    b.HasOne("NVR.Core.Entities.StorageProfile", "StorageProfile")
                        .WithMany("Cameras")
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StorageProfile");
                });

            modelBuilder.Entity("NVR.Core.Entities.CameraAnalyticsSnapshot", b =>
                {
                    b.HasOne("NVR.Core.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("NVR.Core.Entities.CameraEvent", b =>
                {
                    b.HasOne("NVR.Core.Entities.Camera", "Camera")
                        .WithMany("Events")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("NVR.Core.Entities.CameraUserAccess", b =>
                {
                    b.HasOne("NVR.Core.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVR.Core.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NVR.Core.Entities.PtzPreset", b =>
                {
                    b.HasOne("NVR.Core.Entities.Camera", "Camera")
                        .WithMany("PtzPresets")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("NVR.Core.Entities.Recording", b =>
                {
                    b.HasOne("NVR.Core.Entities.Camera", "Camera")
                        .WithMany("Recordings")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVR.Core.Entities.StorageProfile", "StorageProfile")
                        .WithMany()
                        .HasForeignKey("StorageProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("StorageProfile");
                });

            modelBuilder.Entity("NVR.Core.Entities.RecordingChunk", b =>
                {
                    b.HasOne("NVR.Core.Entities.Recording", "Recording")
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("NVR.Core.Entities.RecordingSchedule", b =>
                {
                    b.HasOne("NVR.Core.Entities.Camera", "Camera")
                        .WithMany("RecordingSchedules")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("NVR.Core.Entities.UserCameraLayout", b =>
                {
                    b.HasOne("NVR.Core.Entities.Camera", "Camera")
                        .WithMany("UserLayouts")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVR.Core.Entities.AppUser", null)
                        .WithMany("CameraLayouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("NVR.Core.Entities.AppUser", b =>
                {
                    b.Navigation("CameraLayouts");
                });

            modelBuilder.Entity("NVR.Core.Entities.Camera", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PtzPresets");

                    b.Navigation("RecordingSchedules");

                    b.Navigation("Recordings");

                    b.Navigation("UserLayouts");
                });

            modelBuilder.Entity("NVR.Core.Entities.StorageProfile", b =>
                {
                    b.Navigation("Cameras");
                });
#pragma warning restore 612, 618
        }
    }
}
